# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e69fc49b127b94e9b82d03f260bedadff82972fee0e12b24e612199c3a6413338835953bb3a6757a47e9f95369da1169615274b1ec5f02256443844831ac61

test:
  secret_key_base: ec2b2013e81d4199102cf21763d3819c7e643e3ba698af0c6bc2af8c58a859797618ab4844438a733a079fa38c9c0063850298dc66405005dfd81c1b5367b732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
